# Generated by Django 3.1.2 on 2020-10-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField(help_text='X axis', null=True)),
                ('Y', models.FloatField(help_text='Y axis', null=True)),
                ('Unique_Squirrel_ID', models.CharField(blank=True, help_text='ID', max_length=30)),
                ('Shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Shift AM/PM', max_length=8)),
                ('Date', models.IntegerField(help_text='Date')),
                ('Age', models.CharField(blank=True, choices=[('Juvenile', 'Juvenile'), ('Adult', 'Adult'), ('', '')], help_text='Age Group', max_length=30)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('', '')], help_text='Primary fur color', max_length=30)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), ('', '')], help_text='Location', max_length=30)),
                ('Specific_Location', models.CharField(blank=True, help_text='Specific Location', max_length=180)),
                ('Running', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', help_text='Running Status', max_length=8, null=True)),
                ('Chasing', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', help_text='Chasing Status', max_length=8, null=True)),
                ('Climbing', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', help_text='Climbing status', max_length=8, null=True)),
                ('Eating', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', help_text='Eating Status', max_length=8, null=True)),
                ('Foraging', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', help_text='Foraging Status', max_length=8, null=True)),
                ('Other_Activities', models.CharField(blank=True, help_text='Other Activities', max_length=100)),
                ('Kuks', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', help_text='Kuks', max_length=8, null=True)),
                ('Quaas', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', help_text='Quaas', max_length=8, null=True)),
                ('Moans', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', help_text='Moans', max_length=8, null=True)),
                ('Tail_flags', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', help_text='Tail flags', max_length=8, null=True)),
                ('Tail_twitches', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', help_text='Tail twitches', max_length=8, null=True)),
                ('Approaches', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', help_text='Approaches', max_length=8, null=True)),
                ('Indifferent', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', help_text='Indifferent', max_length=8, null=True)),
                ('Runs_from', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', help_text='Runs from', max_length=8, null=True)),
            ],
        ),
    ]
