# Generated by Django 3.1.2 on 2020-10-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrels', '0002_auto_20201016_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateField(help_text='Date', null=True),
        ),
    ]
