# Generated by Django 3.1.2 on 2020-10-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrels', '0003_auto_20201016_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.IntegerField(help_text='Date MMDDYYYY', null=True),
        ),
    ]
